WIP
does not work, because `predicates_of` invokes `impl_trait_header` to reorder predicates to avoid bogus ambiguity errors like

```
error[E0283]: type annotations needed: cannot satisfy `Iter: SpecTupleExtend<ExtendA, ExtendB>`
   --> library/core/src/iter/traits/collect.rs:589:74
    |
589 | impl<A, B, ExtendA, ExtendB, Iter> SpecTupleExtend<ExtendA, ExtendB> for Iter
    |                                                                          ^^^^
    |
note: multiple `impl`s satisfying `Iter: SpecTupleExtend<ExtendA, ExtendB>` found
   --> library/core/src/iter/traits/collect.rs:578:1
    |
578 | / impl<A, B, ExtendA, ExtendB, Iter> SpecTupleExtend<ExtendA, ExtendB> for Iter
579 | | where
580 | |     ExtendA: Extend<A>,
581 | |     ExtendB: Extend<B>,
582 | |     Iter: Iterator<Item = (A, B)>,
    | |__________________________________^
...
589 | / impl<A, B, ExtendA, ExtendB, Iter> SpecTupleExtend<ExtendA, ExtendB> for Iter
590 | | where
591 | |     ExtendA: Extend<A>,
592 | |     ExtendB: Extend<B>,
593 | |     Iter: TrustedLen<Item = (A, B)>,
    | |____________________________________^
```